DROP TABLE IF EXISTS Demonym;
CREATE TABLE Demonym(
   Country VARCHAR(35) NOT NULL PRIMARY KEY
  ,Demonym VARCHAR(25) NOT NULL
);
INSERT INTO Demonym(Country,Demonym) VALUES ('Afghanistan','Afghan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Albania','Albanian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Algeria','Algerian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Andorra','Andorran');
INSERT INTO Demonym(Country,Demonym) VALUES ('Angola','Angolan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Anguilla','Anguillan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Antigua and Barbuda','Antiguans');
INSERT INTO Demonym(Country,Demonym) VALUES ('Argentina','Argentine');
INSERT INTO Demonym(Country,Demonym) VALUES ('Armenia','Armenian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Australia','Australian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Austria','Austrian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Azerbaijan','Azerbaijani');
INSERT INTO Demonym(Country,Demonym) VALUES ('The Bahamas','Bahamian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Bahrain','Bahraini');
INSERT INTO Demonym(Country,Demonym) VALUES ('Bangladesh','Bangladeshi');
INSERT INTO Demonym(Country,Demonym) VALUES ('Barbados','Barbadian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Belarus','Belarusian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Belgium','Belgian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Belize','Belizean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Benin','Beninese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Bermuda','Bermudian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Bhutan','Bhutanese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Bolivia','Bolivian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Bosnia and Herzegovina','Bosnian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Botswana','Batswana');
INSERT INTO Demonym(Country,Demonym) VALUES ('Brazil','Brazilian');
INSERT INTO Demonym(Country,Demonym) VALUES ('British Virgin Islands','British Virgin Islander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Brunei','Bruneian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Bulgaria','Bulgarian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Burkina Faso','Burkinabe');
INSERT INTO Demonym(Country,Demonym) VALUES ('Burundi','Burundian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Cambodia','Cambodian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Cameroon','Cameroonian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Canada','Canadian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Cape Verde','Cape Verdian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Cayman Islands','Caymanian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Central African Republic','Central African');
INSERT INTO Demonym(Country,Demonym) VALUES ('Chad','Chadian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Chile','Chilean');
INSERT INTO Demonym(Country,Demonym) VALUES ('China','Chinese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Christmas Island','Christmas Islander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Cocos Islands','Cocos Islander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Colombia','Colombian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Comoros','Comoran');
INSERT INTO Demonym(Country,Demonym) VALUES ('Congo, Republic of the','Congolese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Congo, Democratic Republic of the','Congolese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Costa Rica','Costa Rican');
INSERT INTO Demonym(Country,Demonym) VALUES ('Cote d''Ivoire','Ivorian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Croatia','Croat');
INSERT INTO Demonym(Country,Demonym) VALUES ('Cuba','Cuban');
INSERT INTO Demonym(Country,Demonym) VALUES ('Cyprus','Cypriot');
INSERT INTO Demonym(Country,Demonym) VALUES ('Czech Republic','Czech');
INSERT INTO Demonym(Country,Demonym) VALUES ('Denmark','Dane');
INSERT INTO Demonym(Country,Demonym) VALUES ('Djibouti','Djibouti');
INSERT INTO Demonym(Country,Demonym) VALUES ('Dominica','Dominican');
INSERT INTO Demonym(Country,Demonym) VALUES ('Dominican Republic','Dominican');
INSERT INTO Demonym(Country,Demonym) VALUES ('East Timor','East Timorese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Ecuador','Ecuadorean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Egypt','Egyptian');
INSERT INTO Demonym(Country,Demonym) VALUES ('El Salvador','Salvadoran');
INSERT INTO Demonym(Country,Demonym) VALUES ('England','English');
INSERT INTO Demonym(Country,Demonym) VALUES ('Equatorial Guinea','Equatorial Guinean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Eritrea','Eritrean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Estonia','Estonian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Ethiopia','Ethiopian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Falkland Islands','Falkland Islander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Fiji','Fijian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Finland','Finn');
INSERT INTO Demonym(Country,Demonym) VALUES ('France','French');
INSERT INTO Demonym(Country,Demonym) VALUES ('French Guiana','French Guianese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Gabon','Gabonese');
INSERT INTO Demonym(Country,Demonym) VALUES ('The Gambia','Gambian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Georgia','Georgian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Germany','German');
INSERT INTO Demonym(Country,Demonym) VALUES ('Ghana','Ghanaian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Gibraltar','Gibraltarian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Greece','Greek');
INSERT INTO Demonym(Country,Demonym) VALUES ('Greenland','Greenlander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Grenada','Grenadian or Grenadan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Guadeloupe','Guadeloupean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Guatemala','Guatemalan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Guernsey','Channel Islander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Guinea','Guinean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Guinea-Bissau','Guinea-Bissauan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Guyana','Guyanese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Haiti','Haitian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Honduras','Honduran');
INSERT INTO Demonym(Country,Demonym) VALUES ('Hong Kong','Hong Kong Chinese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Hungary','Hungarian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Iceland','Icelander');
INSERT INTO Demonym(Country,Demonym) VALUES ('India','Indian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Indonesia','Indonesian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Iran','Iranian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Iraq','Iraqi');
INSERT INTO Demonym(Country,Demonym) VALUES ('Ireland','Irish');
INSERT INTO Demonym(Country,Demonym) VALUES ('Isle of Man','Manx');
INSERT INTO Demonym(Country,Demonym) VALUES ('Israel','Israeli');
INSERT INTO Demonym(Country,Demonym) VALUES ('Italy','Italian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Jamaica','Jamaican');
INSERT INTO Demonym(Country,Demonym) VALUES ('Japan','Japanese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Jordan','Jordanian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Kazakhstan','Kazakhstani');
INSERT INTO Demonym(Country,Demonym) VALUES ('Kenya','Kenyan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Kiribati','I-Kiribati');
INSERT INTO Demonym(Country,Demonym) VALUES ('Korea','Korean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Kuwait','Kuwaiti');
INSERT INTO Demonym(Country,Demonym) VALUES ('Kyrgyz Republic','Kyrgyz');
INSERT INTO Demonym(Country,Demonym) VALUES ('Laos','Laotian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Latvia','Latvian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Lebanon','Lebanese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Lesotho','Basotho');
INSERT INTO Demonym(Country,Demonym) VALUES ('Liberia','Liberian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Libya','Libyan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Liechtenstein','Liechtensteiner');
INSERT INTO Demonym(Country,Demonym) VALUES ('Lithuania','Lithuanian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Luxembourg','Luxembourger');
INSERT INTO Demonym(Country,Demonym) VALUES ('Macedonia','Macedonian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Madagascar','Malagasy');
INSERT INTO Demonym(Country,Demonym) VALUES ('Malawi','Malawian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Malaysia','Malaysian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Maldives','Maldivan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Mali','Malian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Malta','Maltese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Marshall Islands','Marshallese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Martinique','Martiniquais');
INSERT INTO Demonym(Country,Demonym) VALUES ('Mauritania','Mauritanian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Mauritius','Mauritian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Mayotte','Mahorais');
INSERT INTO Demonym(Country,Demonym) VALUES ('Mexico','Mexican');
INSERT INTO Demonym(Country,Demonym) VALUES ('Federated States of Micronesia','Micronesian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Moldova','Moldovan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Monaco','Monacan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Mongolia','Mongolian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Montserrat','Montserratian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Morocco','Moroccan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Mozambique','Mozambican');
INSERT INTO Demonym(Country,Demonym) VALUES ('Myanmar','Burmese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Namibia','Namibian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Nauru','Nauruan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Nepal','Nepalese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Netherlands','Dutch');
INSERT INTO Demonym(Country,Demonym) VALUES ('Netherlands Antilles','Dutch Antillean');
INSERT INTO Demonym(Country,Demonym) VALUES ('New Zealand','New Zealander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Nicaragua','Nicaraguan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Niger','Nigerien');
INSERT INTO Demonym(Country,Demonym) VALUES ('Nigeria','Nigerian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Norway','Norwegian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Oman','Omani');
INSERT INTO Demonym(Country,Demonym) VALUES ('Pakistan','Pakistani');
INSERT INTO Demonym(Country,Demonym) VALUES ('Palau','Palauan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Palestine','Palestinian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Panama','Panamanian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Papua New Guinea','Papua New Guinean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Paraguay','Paraguayan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Peru','Peruvian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Philippines','Filipino');
INSERT INTO Demonym(Country,Demonym) VALUES ('Poland','Pole');
INSERT INTO Demonym(Country,Demonym) VALUES ('Portugal','Portuguese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Puerto Rico','Puerto Rican');
INSERT INTO Demonym(Country,Demonym) VALUES ('Qatar','Qatari');
INSERT INTO Demonym(Country,Demonym) VALUES ('Reunion','Reunionese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Romania','Romanian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Russia','Russian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Rwanda','Rwandan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Saint Helena','Saint Helenian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Saint Kitts and Nevis','Kittian and Nevisian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Saint Lucia','Saint Lucian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Saint Vincent and Grenadines','Saint Vincentian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Samoa','Samoan');
INSERT INTO Demonym(Country,Demonym) VALUES ('San Marino','San Marinese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Sao Tome and Principe','Sao Tomean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Saudi Arabia','Saudi or Saudi Arabian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Scotland','Scottish');
INSERT INTO Demonym(Country,Demonym) VALUES ('Senegal','Senegalese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Serbia and Montenegro','Serbian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Seychelles','Seychellois');
INSERT INTO Demonym(Country,Demonym) VALUES ('Sierra Leone','Sierra Leonean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Singapore','Singaporean');
INSERT INTO Demonym(Country,Demonym) VALUES ('Slovakia','Slovak');
INSERT INTO Demonym(Country,Demonym) VALUES ('Slovenia','Slovene');
INSERT INTO Demonym(Country,Demonym) VALUES ('Solomon Islands','Solomon Islander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Somalia','Somali');
INSERT INTO Demonym(Country,Demonym) VALUES ('South Africa','South African');
INSERT INTO Demonym(Country,Demonym) VALUES ('Spain','Spaniard');
INSERT INTO Demonym(Country,Demonym) VALUES ('Sri Lanka','Sri Lankan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Sudan','Sudanese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Suriname','Surinamer');
INSERT INTO Demonym(Country,Demonym) VALUES ('Swaziland','Swazi');
INSERT INTO Demonym(Country,Demonym) VALUES ('Sweden','Swede');
INSERT INTO Demonym(Country,Demonym) VALUES ('Switzerland','Swiss');
INSERT INTO Demonym(Country,Demonym) VALUES ('Syria','Syrian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Taiwan','Taiwanese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Tajikistan','Tajik');
INSERT INTO Demonym(Country,Demonym) VALUES ('Tanzania','Tanzanian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Thailand','Thai');
INSERT INTO Demonym(Country,Demonym) VALUES ('Togo','Togolese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Tonga','Tongan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Trinidad and Tobago','Trinidadian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Tunisia','Tunisian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Turkey','Turk');
INSERT INTO Demonym(Country,Demonym) VALUES ('Turkmenistan','Turkmen');
INSERT INTO Demonym(Country,Demonym) VALUES ('Tuvalu','Tuvaluan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Uganda','Ugandan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Ukraine','Ukrainian');
INSERT INTO Demonym(Country,Demonym) VALUES ('United Arab Emirates','Emirati');
INSERT INTO Demonym(Country,Demonym) VALUES ('United Kingdom','British');
INSERT INTO Demonym(Country,Demonym) VALUES ('United States','American');
INSERT INTO Demonym(Country,Demonym) VALUES ('Uruguay','Uruguayan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Uzbekistan','Uzbek');
INSERT INTO Demonym(Country,Demonym) VALUES ('Vanuatu','Ni-Vanuatu');
INSERT INTO Demonym(Country,Demonym) VALUES ('Vatican City','Citizen of the Holy See');
INSERT INTO Demonym(Country,Demonym) VALUES ('Venezuela','Venezuelan');
INSERT INTO Demonym(Country,Demonym) VALUES ('Vietnam','Vietnamese');
INSERT INTO Demonym(Country,Demonym) VALUES ('Virgin Islands','Virgin Islander');
INSERT INTO Demonym(Country,Demonym) VALUES ('Wales','Welsh');
INSERT INTO Demonym(Country,Demonym) VALUES ('Yemen','Yemeni');
INSERT INTO Demonym(Country,Demonym) VALUES ('Zambia','Zambian');
INSERT INTO Demonym(Country,Demonym) VALUES ('Zimbabwe','Zimbabwean');
