DROP TABLE CountryCodes;
CREATE TABLE IF NOT EXISTS CountryCodes(
   StateAbb  VARCHAR(3) NOT NULL
  ,ccode     INTEGER  NOT NULL PRIMARY KEY 
  ,StateName VARCHAR(32) NOT NULL
);
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('USA',2,'United States of America');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CAN',20,'Canada');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BHM',31,'Bahamas');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CUB',40,'Cuba');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('HAI',41,'Haiti');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('DOM',42,'Dominican Republic');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('JAM',51,'Jamaica');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TRI',52,'Trinidad and Tobago');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BAR',53,'Barbados');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('DMA',54,'Dominica');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GRN',55,'Grenada');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SLU',56,'St. Lucia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SVG',57,'St. Vincent and the Grenadines');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('AAB',58,'Antigua & Barbuda');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SKN',60,'St. Kitts and Nevis');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MEX',70,'Mexico');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BLZ',80,'Belize');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GUA',90,'Guatemala');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('HON',91,'Honduras');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SAL',92,'El Salvador');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NIC',93,'Nicaragua');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('COS',94,'Costa Rica');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PAN',95,'Panama');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('COL',100,'Colombia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('VEN',101,'Venezuela');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GUY',110,'Guyana');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SUR',115,'Suriname');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ECU',130,'Ecuador');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PER',135,'Peru');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BRA',140,'Brazil');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BOL',145,'Bolivia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PAR',150,'Paraguay');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CHL',155,'Chile');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ARG',160,'Argentina');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('URU',165,'Uruguay');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('UKG',200,'United Kingdom');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('IRE',205,'Ireland');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NTH',210,'Netherlands');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BEL',211,'Belgium');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LUX',212,'Luxembourg');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('FRN',220,'France');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MNC',221,'Monaco');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LIE',223,'Liechtenstein');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SWZ',225,'Switzerland');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SPN',230,'Spain');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('AND',232,'Andorra');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('POR',235,'Portugal');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('HAN',240,'Hanover');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BAV',245,'Bavaria');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GMY',255,'Germany');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GFR',260,'German Federal Republic');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GDR',265,'German Democratic Republic');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BAD',267,'Baden');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SAX',269,'Saxony');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('WRT',271,'Wuerttemburg');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('HSE',273,'Hesse Electoral');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('HSG',275,'Hesse Grand Ducal');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MEC',280,'Mecklenburg Schwerin');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('POL',290,'Poland');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('AUH',300,'Austria-Hungary');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('AUS',305,'Austria');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('HUN',310,'Hungary');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CZE',315,'Czechoslovakia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CZR',316,'Czech Republic');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SLO',317,'Slovakia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ITA',325,'Italy');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PAP',327,'Papal States');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SIC',329,'Two Sicilies');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SNM',331,'San Marino');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MOD',332,'Modena');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PMA',335,'Parma');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TUS',337,'Tuscany');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MLT',338,'Malta');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ALB',339,'Albania');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MNG',341,'Montenegro');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MAC',343,'Macedonia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CRO',344,'Croatia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('YUG',345,'Yugoslavia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BOS',346,'Bosnia and Herzegovina');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('KOS',347,'Kosovo');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SLV',349,'Slovenia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GRC',350,'Greece');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CYP',352,'Cyprus');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BUL',355,'Bulgaria');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MLD',359,'Moldova');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ROM',360,'Romania');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('RUS',365,'Russia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('EST',366,'Estonia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LAT',367,'Latvia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LIT',368,'Lithuania');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('UKR',369,'Ukraine');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BLR',370,'Belarus');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ARM',371,'Armenia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GRG',372,'Georgia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('AZE',373,'Azerbaijan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('FIN',375,'Finland');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SWD',380,'Sweden');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NOR',385,'Norway');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('DEN',390,'Denmark');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ICE',395,'Iceland');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CAP',402,'Cape Verde');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('STP',403,'Sao Tome and Principe');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GNB',404,'Guinea-Bissau');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('EQG',411,'Equatorial Guinea');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GAM',420,'Gambia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MLI',432,'Mali');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SEN',433,'Senegal');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BEN',434,'Benin');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MAA',435,'Mauritania');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NIR',436,'Niger');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CDI',437,'Ivory Coast');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GUI',438,'Guinea');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BFO',439,'Burkina Faso');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LBR',450,'Liberia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SIE',451,'Sierra Leone');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GHA',452,'Ghana');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TOG',461,'Togo');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CAO',471,'Cameroon');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NIG',475,'Nigeria');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('GAB',481,'Gabon');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CEN',482,'Central African Republic');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CHA',483,'Chad');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CON',484,'Congo');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('DRC',490,'Democratic Republic of the Congo');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('UGA',500,'Uganda');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('KEN',501,'Kenya');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TAZ',510,'Tanzania');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ZAN',511,'Zanzibar');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BUI',516,'Burundi');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('RWA',517,'Rwanda');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SOM',520,'Somalia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('DJI',522,'Djibouti');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ETH',530,'Ethiopia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ERI',531,'Eritrea');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ANG',540,'Angola');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MZM',541,'Mozambique');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ZAM',551,'Zambia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ZIM',552,'Zimbabwe');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MAW',553,'Malawi');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SAF',560,'South Africa');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NAM',565,'Namibia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LES',570,'Lesotho');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BOT',571,'Botswana');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SWA',572,'Swaziland');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MAG',580,'Madagascar');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('COM',581,'Comoros');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MAS',590,'Mauritius');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SEY',591,'Seychelles');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MOR',600,'Morocco');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ALG',615,'Algeria');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TUN',616,'Tunisia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LIB',620,'Libya');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SUD',625,'Sudan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SSD',626,'South Sudan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('IRN',630,'Iran');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TUR',640,'Turkey');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('IRQ',645,'Iraq');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('EGY',651,'Egypt');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SYR',652,'Syria');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LEB',660,'Lebanon');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('JOR',663,'Jordan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ISR',666,'Israel');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SAU',670,'Saudi Arabia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('YAR',678,'Yemen Arab Republic');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('YEM',679,'Yemen');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('YPR',680,'Yemen People''s Republic');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('KUW',690,'Kuwait');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BAH',692,'Bahrain');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('QAT',694,'Qatar');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('UAE',696,'United Arab Emirates');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('OMA',698,'Oman');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('AFG',700,'Afghanistan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TKM',701,'Turkmenistan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TAJ',702,'Tajikistan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('KYR',703,'Kyrgyzstan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('UZB',704,'Uzbekistan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('KZK',705,'Kazakhstan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CHN',710,'China');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MON',712,'Mongolia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TAW',713,'Taiwan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('KOR',730,'Korea');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PRK',731,'North Korea');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ROK',732,'South Korea');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('JPN',740,'Japan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('IND',750,'India');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BHU',760,'Bhutan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PAK',770,'Pakistan');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BNG',771,'Bangladesh');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MYA',775,'Myanmar');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SRI',780,'Sri Lanka');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MAD',781,'Maldives');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NEP',790,'Nepal');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('THI',800,'Thailand');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('CAM',811,'Cambodia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('LAO',812,'Laos');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('DRV',816,'Vietnam');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('RVN',817,'Republic of Vietnam');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MAL',820,'Malaysia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SIN',830,'Singapore');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('BRU',835,'Brunei');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PHI',840,'Philippines');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('INS',850,'Indonesia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('ETM',860,'East Timor');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('AUL',900,'Australia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PNG',910,'Papua New Guinea');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NEW',920,'New Zealand');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('VAN',935,'Vanuatu');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('SOL',940,'Solomon Islands');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('KIR',946,'Kiribati');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TUV',947,'Tuvalu');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('FIJ',950,'Fiji');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('TON',955,'Tonga');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('NAU',970,'Nauru');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('MSI',983,'Marshall Islands');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('PAL',986,'Palau');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('FSM',987,'Federated States of Micronesia');
INSERT INTO CountryCodes(StateAbb,ccode,StateName) VALUES ('WSM',990,'Samoa');
